### ISSUE TITLE
entities are replicated on portal

### ISSUE THREAD

**Issue by RedLime** [kyrptonaught/customportalapi#10]
If throw a dropped item, it will be duplicated into multiple items at the existing dimension and target dimension.

+ edit : This bug was not only dropped items,
its all of entities too.

**Comment by kyrptonaught** [comment]
Are you using the 1.16, or 1.17 version?

**Comment by RedLime** [comment]
> Are you using the 1.16, or 1.17 version?

using 1.17(20w05b).

**Comment by kyrptonaught** [comment]
This probably has to do with the fix implemented from the previous issue, I'll see if that can be applied to all entities, not just players. It seems they did change dimension change logic a bit in the snapshots.

**Comment by kyrptonaught** [comment]
This has been fixes in beta 22
