### ISSUE TITLE
1.21 support?

### ISSUE THREAD

**Issue by n-zer** [kyrptonaught/customportalapi#104]
It's been about a month since 1.21 officially released, so I'm just wondering if this is something that's in progress or planned at all. I tried updating the mod myself in case it was simple, but it looks like it may not be terribly straightforward with the addition of `Portal` and `PortalManager`, and I don't understand much of what the mod is doing.

**Comment by MerlinHose** [comment]
I tried to update it myself, but didn't succeed, could you help me?

**Comment by LittleBigPhil** [comment]
Before any official release, you can use this: #105

**Comment by kyrptonaught** [comment]
The port is finished
