### ISSUE TITLE
ModMenu

### ISSUE THREAD

**Issue by spjoes** [kyrptonaught/customportalapi#15]
Using your API on Intellij for my mod, I constantly have to temperarily delete ModMenu from your API (It regens on startup tho) is there anyway to have your API not include ModMenu? And if its absolutely necessary can you either atleast update ModMenu to the latest version in your Build.Gradle OR just make ModMenu not compile in your API? Thanks! And keep up the great work.

Note: If I JUST use the modmenu version that is compiled in your mod, the game crashes because the creator of modmenu has a system in place to crash your game on startup if you use an old version of modmenu

**Comment by kyrptonaught** [comment]
Beta 25 removes mod menu from the dev environment

**Comment by spjoes** [comment]
Not for me? Im running Beta-25.

**Comment by kyrptonaught** [comment]
I apologize, I meant beta 26
