### ISSUE TITLE
NullPointerException in addPortal

### ISSUE THREAD

**Issue by spxctreofficial** [kyrptonaught/customportalapi#2]
This is the crash that I get when I try to add a new portal with the API.

```
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.block.Block.getStateManager()" because "block" is null
	at net.fabricmc.fabric.api.object.builder.v1.world.poi.PointOfInterestHelper.register(PointOfInterestHelper.java:56)
	at net.kyrptonaught.customportalapi.CustomPortalApiRegistry.addPortal(CustomPortalApiRegistry.java:30)
	at net.kyrptonaught.customportalapi.CustomPortalApiRegistry.addPortal(CustomPortalApiRegistry.java:36)
	at com.spxctreofficial.enhancedcraft.registry.portal.ECPortalRegistry.registerPortals(ECPortalRegistry.java:17)
	at com.spxctreofficial.enhancedcraft.registry.ECRegistry.Registry(ECRegistry.java:436)
	at com.spxctreofficial.enhancedcraft.EnhancedCraft.onInitialize(EnhancedCraft.java:17)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 12 more
```

I'm not sure what could be the issue, but this happens regardless of what I set as the frameBlock.

**Comment by kyrptonaught** [comment]
Can you post the code you are using? Is it in your initializer? After the desired block has been initialized?

**Comment by kyrptonaught** [comment]
Can you add System.out.println(block) before that call to verify if the desired block is initialized. Just doubled checked my code and ran in dev and prod and didnt have any issues.

**Comment by spxctreofficial** [comment]
The issue seemed to only show up when used in an external mod utilizing the API. The problem is most likely an issue with the mappings that causes the PortalBlock to become null. I rectified this by copying your code for the CustomPortalBlock, and then creating my own class with the same code, but for my mod. Alternatively, a friend of mine redefined your custom portal block in their own ModInitializer, and copied over the texture for the portal block so that the texture would appear normally.

I guess you could say that this issue has been resolved and can be closed, but I would like to suggest you add an extra step to the README regarding this.

Thanks for your efforts and your creation of this API.

**Comment by kyrptonaught** [comment]
Ah I know exactly why this is happening, it's a load order issue. The CustomPortaBlock gets created during CustomPortalApi's mod initializer. If your mod loads before CustomPortalApi gets to, the block will be null. I will instead create a workaround so the block gets created the first time it is requested, so you're workaround won't be necessary. Thank you for bringing this to my attention, I completely overlooked this

**Comment by spxctreofficial** [comment]
You're welcome! Thanks for creating the amazing API.

**Comment by kyrptonaught** [comment]
Can you try beta14? Without your custom portal block. It should fix the issue

**Comment by spxctreofficial** [comment]
The issue is now resolved. Thanks for your help and your custom portal API!

**Comment by kwpugh** [comment]
Kyrptonaught:  can you please check out the above new issue to see if it is the same issue?   My Gobber 1.16.5 mod is compiled with:

	//Custom Portals
	modImplementation 'net.kyrptonaught:customportalapi:0.0.1-beta18-1.16'
	include 'net.kyrptonaught:customportalapi:0.0.1-beta18-1.16'

**Comment by kyrptonaught** [comment]
Can you try the latest beta for 1.16, beta32 and verify if it's still an issue?

**Comment by kwpugh** [comment]
ok, will do.

**Comment by kwpugh** [comment]
Alright, updating to beta32 seemed to do the trick.

Thank you.
