### ISSUE TITLE
Custom Portal API Not Creating Portals When Teleporting 

### ISSUE THREAD

**Issue by JamesF22293** [kyrptonaught/customportalapi#20]
Whenever I teleport to any dimension using this API, it does not automatically create a portal in the dimension teleported to, regardless if it is a custom dimension, nether, or end. This happens in 21w16a and 21w14a. Not in 1.16.5, and I have not tested other 1.17 snapshots.

**Comment by kyrptonaught** [comment]
I'll have to update to the newer snapshots, I haven't done that in a while

**Comment by kyrptonaught** [comment]
Custom portal api has been ported to 1.17
