### ISSUE TITLE
Bintray downloads not working

### ISSUE THREAD

**Issue by Jack-Papel** [kyrptonaught/customportalapi#21]
The download on the main page gives a 404 error.
There's also a 403 Forbidden! on https://dl.bintray.com/kyrptonaught/customportalapi/net/kyrptonaught/customportalapi/0.0.1-beta29-1.16/customportalapi-0.0.1-beta29-1.16.pom
This is probably an issue with Bintray, and if so will likely be a permanent issue with bintray. 
It likely has something to do with this announcement regarding end of support for bintray on may 1st: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by matthew-periut** [comment]
https://github.bajins.com/kyrptonaught
![image](https://user-images.githubusercontent.com/18296791/116827311-579f3e80-ab66-11eb-8476-67a128e838fd.png)
This error also is related, the best solution considering end of support is to transfer platforms

**Comment by kyrptonaught** [comment]
I apologize guys, I didn't get the time to make the switch before the EOL. 

For now you can use jitpack.

**Comment by IronOverheat** [comment]
Hi, what is the jitpack url for customportalapi?

**Comment by kyrptonaught** [comment]
https://jitpack.io/#kyrptonaught/customportalapi/-SNAPSHOT

**Comment by bobdoby** [comment]
not working for me

**Comment by kyrptonaught** [comment]
I did move cpa to my own maven server. Use the following url 

Http://maven.kyrptonaught.dev

**Comment by kyrptonaught** [comment]
This has been fixed, view the readme for updated instructions.
