### ISSUE TITLE
Issue Downloading Repository

### ISSUE THREAD

**Issue by bobdoby** [kyrptonaught/customportalapi#24]
Hey, sorry I am new at making mods, when i tried to download your repository i got back an error.
i put this in my build.gradle
dependencies {
	modImplementation "net.kyrptonaught:customportalapi:${project.loader_version}"
	include "net.kyrptonaught:customportalapi:${project.loader_version}"
}

and i recieved this error

Could not GET 'https://dl.bintray.com/kyrptonaught/customportalapi/net/kyrptonaught/customportalapi/0.11.3/customportalapi-0.11.3.pom'. Received status code 403 from server: Forbidden
Disable Gradle 'offline mode' and sync project

please note, my gradle is not offline
even when i put in the latest version i get the same error.
please assist

**Comment by kyrptonaught** [comment]
Bintray has been shut down unfortunately.

I did move cpa to my own maven server. Use the following url 

Http://maven.kyrptonaught.dev

**Comment by kyrptonaught** [comment]
Also you should be using a version of cpa for its version tag, not {project-loader}

The aether has customportalapi working, see https://github.com/devs-immortal/The-Aether

**Comment by bobdoby** [comment]
still having issues

repositories {
		maven { url "http://maven.kyrptonaught.dev" }

		mavenCentral()
	}

dependencies {
		modImplementation "net.kyrptonaught:customportalapi:${project.customportalapi_version}"
		include "net.kyrptonaught:customportalapi:${project.customportalapi_version}"
	
		minecraft "com.mojang:minecraft:${project.minecraft_version}"
		mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
		modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

		
		modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

		
	}



I just coppied this from aether and i am still having issues -_-

**Comment by bobdoby** [comment]
sorry i forget to add the error

Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'customportalapi_version' for root project 'fabric-example-mod-master' of type org.gradle.api.Project.

**Comment by bobdoby** [comment]
A problem occurred configuring root project 'fabric-example-mod-master'.
> Failed to notify project evaluation listener.
   > Could not resolve all dependencies for configuration ':mappings'.
      > Using insecure protocols with repositories, without explicit opt-in, is unsupported. Switch Maven repository 'maven(http://maven.kyrptonaught.dev)' to redirect to a secure protocol (like HTTPS) or allow insecure protocols. See https://docs.gradle.org/7.0.2/dsl/org.gradle.api.artifacts.repositories.UrlArtifactRepository.html#org.gradle.api.artifacts.repositories.UrlArtifactRepository:allowInsecureProtocol for more details. 
   > java.lang.NullPointerException (no error message)

**Comment by bobdoby** [comment]
now i am very confused

**Comment by bobdoby** [comment]
now i am very confused

**Comment by kyrptonaught** [comment]
Did you include the custom portal version in your gradle.properties? See aether

**Comment by kyrptonaught** [comment]
Feel free to dm me on discord: Kyrptonaught#4239

**Comment by kyrptonaught** [comment]
This has been fixed, view the readme for updated instructions.

**Comment by warior456** [comment]
does not work
