### ISSUE TITLE
[1.17.1] Duplicate portal created when returning from a nether-like dimension

### ISSUE THREAD

**Issue by kwpugh** [kyrptonaught/customportalapi#26]
Hi, 

I use the api in my Mining Dimensions mod.   I have four dimensions that I add and it works just fine with three of them.  But one dimension it does not return to the original portal, but creates a new portal about 50 blocks away.   This happens in single player and on a dedicated server.

I compile my mod with:  0.0.1-beta37-1.17

Mining Dimensions latest sources:   https://github.com/kwpugh/mining_Dimensions-1.17/tree/1.17.0/src/main
- it is the tethering_dim which has the problem

Any help you can provide would be greatly appreciated.

Regards

Kevin

**Comment by kyrptonaught** [comment]
Duplicate of #16. This is an issue I've been chasing for some time now. I can't quite seem to figure out whats causing it. I might just have to use a bandaid fix of just saving the players coords to return to later when using a portal.

**Comment by kyrptonaught** [comment]
Hey sorry for the delay, beta 41 should significantly improve this.

**Comment by kwpugh** [comment]
I  haven't seen any reports  of the duplicate portals since the 42 update.
