### ISSUE TITLE
[1.17.1] Cycling back and forth between dimensions on servers

### ISSUE THREAD

**Issue by kwpugh** [kyrptonaught/customportalapi#27]
API:  beta 37
Minecraft:  1.17.1
Fabric:  0.36.1+1.17
My mod:  https://github.com/kwpugh/mining_Dimensions-1.17

System log:  https://gist.github.com/kwpugh/a2ab8238c286bb66eca772b9edf0f799

When entering one of my modded portals, while on a server, the player cycles back-and-forth between dimensions at least a dozen times and may stop either in the dest or the original dim, randomly.  This seems to only happen on server, single player is fine.

**Comment by kyrptonaught** [comment]
Can you try beta 38? I think I fixed this

**Comment by kwpugh** [comment]
I did some quick testing and it appears that beta38 might have fixed it.

I did notice that my portal to a nether-like dimension stills creates a new portal in the overworld, about 50 blocks from the original.

Also, did you leave some debug statements in?  Noticed this in the console:
[21.07 07:26:37] [Server] [Server thread/INFO]: [STDOUT]: Before TP: true
[21.07 07:26:37] [Server] [Server thread/INFO]: [STDOUT]: After TP: true

Regards.

**Comment by CDAGaming** [comment]
@kwpugh Debug statements will be removed in b39 (At least that's what Kyrpt told me in discord) +1

**Comment by kyrptonaught** [comment]
Yes this has been fixed in beta-39

**Comment by kyrptonaught** [comment]
Hey sorry for the delay, beta 41 should significantly improve the linking of portals.

**Comment by quentfr21** [comment]
happend to me only in creative while it make portal instant teleport

**Comment by kyrptonaught** [comment]
Was this recent with beta 41+?

**Comment by quentfr21** [comment]
i use latest mining dimension and space age but no idea what is the version used sorry 
that happend to me when i make the report

**Comment by kwpugh** [comment]
I'll update and let you know.

**Comment by quentfr21** [comment]
sorry for the delay look like ok now no more instant tp between dim

**Comment by kwpugh** [comment]
No more reports of this on my end.
