### ISSUE TITLE
All Portals Link back to the original.

### ISSUE THREAD

**Issue by sbdonslaught** [kyrptonaught/customportalapi#28]
Hello,

I am using this mod pack: https://www.curseforge.com/minecraft/modpacks/medieval-minecraft-fabric/files/3384600
Which uses this Aether mod: https://www.curseforge.com/minecraft/mc-mods/aether

Whenever someone creates a portal to the aether, they appear at my (original) portal, and obviously, when re-entering the portal to come back to the overworld, they return at my home and not theirs.

I can provide a video if needed.

**Comment by kyrptonaught** [comment]
Hey sorry for the delay, beta 41 should significantly improve this

**Comment by sbdonslaught** [comment]
Thank you for the reply! <3
