### ISSUE TITLE
Alternative means of portal lighting

### ISSUE THREAD

**Issue by Jack-Papel** [kyrptonaught/customportalapi#29]
Custom portals can't be lit via dispensers or other means, like the nether portal can.

https://github.com/devs-immortal/The-Aether/issues/383

https://github.com/devs-immortal/The-Aether/issues/384

**Comment by kyrptonaught** [comment]
I'll investigate tonight!

**Comment by kyrptonaught** [comment]
This has been fixed in beta 41
