### ISSUE TITLE
Crash on Server

### ISSUE THREAD

**Issue by spxctreofficial** [kyrptonaught/customportalapi#3]
This happens when I put my mod in the server with the customportalapi as an `include`.

https://paste.mod.gg/zojurijiza.sql

Any ideas on to what the problem should be?

To replicate: use a custom external mod that uses the customportalapi being ran on the server.

**Comment by kyrptonaught** [comment]
Can you verify you are using the most recent version of the api? I think that was fixed already

**Comment by spxctreofficial** [comment]
Possibly. I do believe I am using beta-14, so I will test out beta-15 and see if the issue persists.

**Comment by spxctreofficial** [comment]
Yep, the issue was fixed in beta-15.
