### ISSUE TITLE
does datapack portal work ?

### ISSUE THREAD

**Issue by quentfr21** [kyrptonaught/customportalapi#31]
hello 

i try to make a datapack to go to a new dimension already created but the portal never ignte

thanks in advance

Edit: sorry it's work now i make a mistake the only thing is teleport back/forth from dimension on my server maybe this will be fixed when i got mining dimension updated to your latest version

Edit2 i thing i finally know why i teleport again and again it's due to creative mod that make you instant teleport when you pass a portal

thanks again and you may close this issue

**Comment by kyrptonaught** [comment]
Whats creative mod? Do you mean creative mode?

**Comment by quentfr21** [comment]
> Whats creative mod? Do you mean creative mode?

yep sorry creative mode :)
