### ISSUE TITLE
Server crash after recently creating custom portal; projectile

### ISSUE THREAD

**Issue by ThatScar** [kyrptonaught/customportalapi#32]
I'll get straight to the point - server crash because of NullPointerException
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_36456(float)" because "entity" is null
	at net.kyrptonaught.customportalapi.util.CustomTeleporter.TPToDim(CustomTeleporter.java:46)
	at net.kyrptonaught.customportalapi.CustomPortalBlock.onEntityCollision(CustomPortalBlock.java:116)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.onEntityCollision(AbstractBlock:926)
	at net.minecraft.entity.Entity.checkBlockCollision(Entity:1035)
	at net.minecraft.entity.projectile.PersistentProjectileEntity.tick(PersistentProjectileEntity:280)
	at mod.azure.doom.entity.projectiles.ChaingunBulletEntity.tick(ChaingunBulletEntity.java:126)
	at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld:655)
[at ...]
```

I don't know if this was a problem with the portal generation making a mess or the projectile entering a portal weirdly but a crash is a crash that could be avoided - hopefully accounting for null parameters.

Modpack used: [Another Quality Modpack 2](https://www.curseforge.com/minecraft/modpacks/another-quality-modpack-2) v2.7.0c
Mod used: [Custom Portals by palyon_1](https://www.curseforge.com/minecraft/mc-mods/custom-portals) v2.1.0
Custom Portal API version 0.0.1-beta41-1.17
Full log and **crash report** (scroll down to the end for the latter): https://gist.github.com/ThatScar/10f77bcf5c299ec6acb698e08287b1c5
Full description of what happened: A player entered a custom portal to the nether. I don't know if the portal has been entered before by other players but I am fairly sure this act of entrance created a new portal on the nether side. The server immediately crashed when a player teleported using it. Upon reloading the server, it crashed again when the player connected. Later, a different player ThatScar (me) connected and there was no crash; portal was destroyed by hand and the issue stopped happening.
A screenshot of the portal in question: https://imgur.com/4soprGQ

Hope this helps somebody,
ThatScar

**Comment by kyrptonaught** [comment]
Thank you for the report, I will investigate the crash shortly.

Also worth mentioning that CustomPortalapi is not affiliated with the CustomPortals mod you linked. They just have similar names serving a similar function. I had created this api before I knew of its existence

**Comment by kyrptonaught** [comment]
Is the portal shown in that screenshot man made?

**Comment by kyrptonaught** [comment]
Ah just saw you were using beta-41, this was already fixed in a later beta. Beta-44 is the latest release as of writing this

**Comment by ThatScar** [comment]
Thank you for replying.
P.S. It seems the portal was actually ghast-made!
