### ISSUE TITLE
[1.18-21w43a] Entering portals crash  game

### ISSUE THREAD

**Issue by kwpugh** [kyrptonaught/customportalapi#33]
Crash report: https://gist.github.com/kwpugh/b483deba282078c629674a4b57597689

Looks like  Mojang changed a  class name.

**Comment by kyrptonaught** [comment]
beta45v2 was just pushed with a fix for 21w43a

**Comment by kwpugh** [comment]
Confirmed, just tested, no crash.  Thank you.
