### ISSUE TITLE
[1.18 - 21W43A] Portal placed on roof of Nether type dimensions

### ISSUE THREAD

**Issue by kwpugh** [kyrptonaught/customportalapi#35]
Hi, on latest beta45v2, the portal is placed on the roof of my nether like dimension.

I define the dim this way like the vanilla Nether:

{
  "logical_height": 128,
  "infiniburn": "minecraft:infiniburn_nether",
  "effects": "minecraft:the_nether",
  "ambient_light": 0.1,
  "respawn_anchor_works": true,
  "has_raids": false,
  "min_y": 0,
  "height": 256,
  "natural": false,
  "coordinate_scale": 8.0,
  "piglin_safe": true,
  "bed_works": false,
  "fixed_time": 18000,
  "has_skylight": false,
  "has_ceiling": true,
  "ultrawarm": true
}

**Comment by kyrptonaught** [comment]
Ah I know why, the mapping that changed had to do with getting the logical top. I think I changed that mapping to the incorrect thing, likely the actual top of the world.

**Comment by kyrptonaught** [comment]
This was fixed in beta45v3

**Comment by kwpugh** [comment]
okie dokie, I will  update and test.

**Comment by kwpugh** [comment]
seems to work great, I did a number of portals at different levels and they all worked fine.
