### ISSUE TITLE
Falt Portals dont seem to work

### ISSUE THREAD

**Issue by frikinjay** [kyrptonaught/customportalapi#36]
I see in the latest commit that flat portals are possible now but using this i cant seem to activate the portal with a 5x5 obsidian portal with a flint and steel.

`CustomPortalBuilder.beginPortal()
		    .frameBlock(Blocks.OBSIDIAN)
		    .destDimID(new Identifier("the_nether"))
		    .tintColor(131,66,184)
		    .flatPortal()
		    .registerPortal();
`

![image](https://user-images.githubusercontent.com/88995340/139577329-a09c1d99-8a2b-4990-a1c0-801a5387e04e.png)

**Comment by kyrptonaught** [comment]
Can you try a different block? You also probably have an error in the log about registering a portal that already exists.

When registering a portal it checks for conflicting portals, but doesn't check if they are of different types. It's most likely detecting this as a conflict

**Comment by frikinjay** [comment]
I see, I'll try it with a different block. It'd be nice if it detects different types of portals for the same block types.

**Comment by frikinjay** [comment]
It works with other blocks. Thanks for the help : ) But yeah the above thing would be nice as a feature if you're looking for enhancement suggestions.

**Comment by kyrptonaught** [comment]
I did it to help avoid confusion for the player. They may make a flat version of a portal and expect it to go to the same place. Not sure if it's really a big deal but that was my thinking

**Comment by frikinjay** [comment]
Ah fair, well i'll close it since its working as intended.
