### ISSUE TITLE
Support for Block Entities for Custom Portal Block

### ISSUE THREAD

**Issue by frikinjay** [kyrptonaught/customportalapi#38]
Support for Block Entities for Custom Portal Block to be able to use textures/shaders like End portal.

**Comment by kyrptonaught** [comment]
There shouldn't be anything stopping you from using a custom portal block like the aether and just making it implement BlockEntityProvider

**Comment by frikinjay** [comment]
So I'll have to recreate the portal block to use it? I was hoping not to have to do that, will be quite the headache.

**Comment by kyrptonaught** [comment]
Not quite, you'll to make and register a block. Have that block extend CustomPortalBlock. Then supply it to your CustomPortalBuilder portal instance. That's it, well I guess you'll also need all the traditional json bloat that comes with making a new block. The block is then free to be customized and used however you'd like. Can can then make this block implement BlockEntityProvider to have a BE

**Comment by frikinjay** [comment]
I see, yeah I made it work somewhat just figuring out some vanilla code to use the renderer for the end portal. Thanks for the help!
