### ISSUE TITLE
Portals only work on development enviroments.

### ISSUE THREAD

**Issue by diabolical17** [kyrptonaught/customportalapi#4]
Self Explanatory

**Comment by kyrptonaught** [comment]
Anything of interest in the logs?

**Comment by kyrptonaught** [comment]
Assuming this is to do with the aether?

**Comment by kyrptonaught** [comment]
Oh it actually looks like I broke all portals in general, whoops

**Comment by diabolical17** [comment]
Sorry for not responding fast, my notifs are filled to the brim on GH currently.

Yeah its aether related, some people had it on old worlds, could just be non-compatibility from different versions of the mod. I'll add a disclaimer.

**Comment by kyrptonaught** [comment]
It might even be vanilla or fabric related, Bc no dimensions at all we're registered. Vanilla Nether portal and end included. If you can find a way to recreate lmk and I'll just make sure it isn't Bc of customportals

**Comment by diabolical17** [comment]
I found the bug: Fabric Loader needs to be 0.28 exact.
