### ISSUE TITLE
[1.18] Java 17 in mod mixin json causes server to fail  to start

### ISSUE THREAD

**Issue by kwpugh** [kyrptonaught/customportalapi#40]
Know issue that Mixin compatibility needs to be Java 16 in 1.18-rc1+, for now at least.

<img width="664" alt="Screen Shot 2021-11-28 at 8 02 55 AM" src="https://user-images.githubusercontent.com/8809210/143771219-03c0ca0a-fe1d-4923-953f-c5601d1b80ca.png">

Log:   https://gist.github.com/kwpugh/4ad1c8e1bc684f257ca3455a0a8ab996

**Comment by kyrptonaught** [comment]
I released beta46v2 to fix this

**Comment by kwpugh** [comment]
Got it.  Thanks.
