### ISSUE TITLE
[1.18] Crash when player enters a portal

### ISSUE THREAD

**Issue by kwpugh** [kyrptonaught/customportalapi#42]
crash log: https://gist.github.com/kwpugh/2177ad20ad17fb382f8b012ed35fa969

**Comment by kyrptonaught** [comment]
It looks like it crashed while generating a chunk. I don't think this is bc of cpa.

**Comment by kwpugh** [comment]
It was caused by Better Nether.  

Notes from last update of Better Nether:
Changes:

Removed NetherCity from the overworld (you can bring it back through the generator config (**generator.world.cities.overwrold = true**)
Removed fixed world height when populating the nether.
