### ISSUE TITLE
[22w16b] Crash on game start up

### ISSUE THREAD

**Issue by kwpugh** [kyrptonaught/customportalapi#49]
Report: https://gist.github.com/kwpugh/c159b8d2e6a26bc6ff8e3eb54f307bae

Looks like  something got renamed.

**Comment by kyrptonaught** [comment]
I cannot recreate this using version: 0.0.1-beta50-1.19snapshot and 22w14a

**Comment by kwpugh** [comment]
Hmmm.  I just tried 3 times in a row and same crash with the minimal:
- Mining Dims 1.4.6
- Cloth Config 6.2.57
- Fabric API  0.49.6+1.19

Using MultiMC launcher 0.6.16-develop-3263

https://gist.github.com/kwpugh/ced323a6b7c7ded88cd58eddca47d840

Mining Dims is built on Loom 0.12, does that matter?

**Comment by kyrptonaught** [comment]
Where are you getting "customportalapi 0.0.1-beta50-1.19" from? The version on the maven is "0.0.1-beta50-1.19snapshot"

That is what's causing it. Mining dims crashes alone, but if i install the version from the maven it's fine

**Comment by kwpugh** [comment]
that is the version I am using
<img width="697" alt="Screen Shot 2022-04-11 at 11 50 08 PM" src="https://user-images.githubusercontent.com/8809210/162876760-f6a7e38d-7322-4e83-bc88-c1a306700338.png">

**Comment by kyrptonaught** [comment]
I wonder if its a weird cache thing, I re-uploaded the build and tested support for 22w15a

Try this: 0.0.1-beta50v2-1.19snapshot

**Comment by kwpugh** [comment]
Even with the latest:
<img width="695" alt="Screen Shot 2022-04-21 at 5 30 26 PM" src="https://user-images.githubusercontent.com/8809210/164563793-afefbe07-d430-4617-b600-aba61eb26e67.png">

Yields:
<img width="695" alt="Screen Shot 2022-04-21 at 5 46 37 PM" src="https://user-images.githubusercontent.com/8809210/164564244-0de141c8-dfc2-4bbd-a471-f5e33bdb1bca.png">

and crashes:
https://gist.github.com/kwpugh/01e2dc7712fd5b53136aeee43e3761a2

**Comment by kwpugh** [comment]
Moot point now.
