### ISSUE TITLE
Error importing dependency

### ISSUE THREAD

**Issue by MythicDev** [kyrptonaught/customportalapi#53]
Whenever I try use this in my mod, I get this error.

The supplied phased action failed with an exception.
A problem occurred configuring root project 'fabric-example-mod-1.19'.
Failed to setup Minecraft, org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':modImplementation'.
Could not resolve all dependencies for configuration ':modImplementation'.
Could not find net.kyrptonaught:customportalapi:V0.0.1-BETA52-1.19.
Searched in the following locations:
  - file:/C:/Users/USERNAME/Downloads/sculkportaldimension/fabric-example-mod-1.19/.gradle/loom-cache/remapped_mods/net/kyrptonaught/customportalapi/V0.0.1-BETA52-1.19/customportalapi-V0.0.1-BETA52-1.19.pom
  - https://maven.fabricmc.net/net/kyrptonaught/customportalapi/V0.0.1-BETA52-1.19/customportalapi-V0.0.1-BETA52-1.19.pom
  - https://libraries.minecraft.net/net/kyrptonaught/customportalapi/V0.0.1-BETA52-1.19/customportalapi-V0.0.1-BETA52-1.19.pom
  - https://libraries.minecraft.net/net/kyrptonaught/customportalapi/V0.0.1-BETA52-1.19/customportalapi-V0.0.1-BETA52-1.19.jar
  - https://repo.maven.apache.org/maven2/net/kyrptonaught/customportalapi/V0.0.1-BETA52-1.19/customportalapi-V0.0.1-BETA52-1.19.pom
  - file:/C:/Users/USERNAME/.gradle/caches/fabric-loom/V0.0.1-BETA52-1.19/customportalapi.jar
  - file:/C:/Users/USERNAME/Downloads/sculkportaldimension/fabric-example-mod-1.19/.gradle/loom-cache/V0.0.1-BETA52-1.19/customportalapi.jar
  - https://maven.kyrptonaught.dev/net/kyrptonaught/customportalapi/V0.0.1-BETA52-1.19/customportalapi-V0.0.1-BETA52-1.19.pom
Required by:
    project :

**Comment by kyrptonaught** [comment]
In your build.gradle you need to remove the "V" in your modimplementation for customportalapi. It also may need to be lowercase
Like so: `modImplementation 'net.kyrptonaught:customportalapi:0.0.1-beta52-1.19'`

**Comment by MythicDev** [comment]
Thanks for replying so quick, this worked :)
