### ISSUE TITLE
Portal doesn't light

### ISSUE THREAD

**Issue by MythicDev** [kyrptonaught/customportalapi#54]
Now I'm sure this is to do with my code but if I could get help as to why this isn't working I would be very grateful, thanks in advance.
public static void registerPortals() {
        CustomPortalBuilder.beginPortal() 
            .frameBlock(Blocks.REINFORCED_DEEPSLATE)
            .lightWithItem(Items.FLINT_AND_STEEL)
            .destDimID(new Identifier("thefell", "my_dimension_id"))
            .tintColor(100, 100, 200)
            .registerPortal();
    }

**Comment by kyrptonaught** [comment]
Remove the lightWithItem line
Portals are lit with fire by default.

**Comment by MythicDev** [comment]
Thanks so much!
