### ISSUE TITLE
[Not an issue] Destination portal spawns in the air

### ISSUE THREAD

**Issue by Dragonissa** [kyrptonaught/customportalapi#62]
Unlike the nether portal, the portal created with this library in the destination dimension is on the same y coordinate, which often results in it flying.

Is there any fix for it?

MC: 1.18.2
Fabric: 0.48.0+1.18.2
Loader: 0.13.3
CPA: 0.0.1-beta52-1.18

![2022-09-27_17 44 19](https://user-images.githubusercontent.com/4233773/192586389-8f01376c-210d-4445-b45f-e6ebe90e6f9a.png)

**Comment by kyrptonaught** [comment]
That likely means it couldn't find a safe place to put the portal, it'll default to the same coords as the entrance portal.

It may not consider the grass block there as safe to hold the portal.

Do you have a link to the src code?

**Comment by Dragonissa** [comment]
> That likely means it couldn't find a safe place to put the portal, it'll default to the same coords as the entrance portal.
> 
> It may not consider the grass block there as safe to hold the portal.
> 
> Do you have a link to the src code?

Ye its my own mod. It might lack a certain block tag?

https://github.com/Dragonisser/CobaltMod-3/blob/42ed0a4e02802878061e62ad196bbe6d501daba4/src/main/java/de/prwh/cobaltmod/core/blocks/CobaltGrassBlock.java

Edit:

I just saw that my grass_block had MATERIAL.PLANT. Not sure how that happened, but that might explain the problem.

Edit:

That was the issue. I switched it to MATERIAL.SOLID_ORGANIC and it works. If i hit an ocean it still doesn't work, but i guess that cant be changed.

![2022-09-28_14 21 17](https://user-images.githubusercontent.com/4233773/192789407-5f630d87-e333-4f68-a7f2-5f4a7e5d6d8f.png)


![2022-09-28_14 20 57](https://user-images.githubusercontent.com/4233773/192789332-588cfed5-af7d-44ed-b484-3bd48897d87f.png)
