### ISSUE TITLE
Error while importing dependency

### ISSUE THREAD

**Issue by SpiceyCereal** [kyrptonaught/customportalapi#69]
A problem occurred configuring root project 'fabric-example-mod-1.19'.
> Could not resolve all files for configuration ':modImplementation'.
   > Could not find net.kyrptonaught:customportalapi:0.0.1-beta59-1.19.
     Searched in the following locations:
       - file:/C:/Users/USERNAME/IdeaProjects/fabric-example-mod-1.19/.gradle/loom-cache/remapped_mods/net/kyrptonaught/customportalapi/0.0.1-beta59-1.19/customportalapi-0.0.1-beta59-1.19.pom
       - file:/C:/Users/USERNAME/.gradle/caches/fabric-loom/minecraftMaven/net/kyrptonaught/customportalapi/0.0.1-beta59-1.19/customportalapi-0.0.1-beta59-1.19.pom
       - file:/C:/Users/USERNAME/IdeaProjects/fabric-example-mod-1.19/.gradle/loom-cache/minecraftMaven/net/kyrptonaught/customportalapi/0.0.1-beta59-1.19/customportalapi-0.0.1-beta59-1.19.pom
       - https://maven.fabricmc.net/net/kyrptonaught/customportalapi/0.0.1-beta59-1.19/customportalapi-0.0.1-beta59-1.19.pom
       - https://libraries.minecraft.net/net/kyrptonaught/customportalapi/0.0.1-beta59-1.19/customportalapi-0.0.1-beta59-1.19.pom
       - https://libraries.minecraft.net/net/kyrptonaught/customportalapi/0.0.1-beta59-1.19/customportalapi-0.0.1-beta59-1.19.jar
       - https://repo.maven.apache.org/maven2/net/kyrptonaught/customportalapi/0.0.1-beta59-1.19/customportalapi-0.0.1-beta59-1.19.pom
     Required by:
         project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
 
 	modImplementation 'net.kyrptonaught:customportalapi:0.0.1-beta59-1.19'
	include 'net.kyrptonaught:customportalapi:0.0.1-beta59-1.19'

Issue #53 didn't help

**Comment by kyrptonaught** [comment]
Did you add the repo to your build.gradle?

`maven { url = "https://maven.kyrptonaught.dev" }`

**Comment by SpiceyCereal** [comment]
I only added the dependency. Was I supposed to add both?

**Comment by SpiceyCereal** [comment]
Thank you! This is my first time using a gradle dependency
