### ISSUE TITLE
[Feature Request] custom y offset

### ISSUE THREAD

**Issue by warior456** [kyrptonaught/customportalapi#71]
when going trough a portal very low in the world (aka ancient city) the portal can't find a safe place because it can't search up to the surface of that dimension and ends up spawning in the air or ground

**Comment by warior456** [comment]
after further inspection it seems that even if the y level is right it still spawns in the air at the exact same y coordinate? How do i fix this? the ground is made from deepslate

**Comment by kyrptonaught** [comment]
This was added in beta 62.

See: CustomPortalBuilder: setPortalSearchYRange and setReturnPortalSearchYRange
