### ISSUE TITLE
Unable to interact with world after changing dimensions via portal

### ISSUE THREAD

**Issue by modderwizard** [kyrptonaught/customportalapi#8]
I'm running in a development environment on Minecraft 21w03a, using fabric_version 0.29.5+1.17, and loader_version 0.11.1.

Using a custom portal to travel between dimensions breaks the player's ability to interact with the world (breaking blocks, tilling grass, etc.). Breaking blocks does work but only if the player is in creative mode. This is also the case when using the portal to travel back to the overworld from the custom dimension.

This can be fixed by quitting and re-joining the game, but it is obviously not desirable to do this every time a custom portal is used.

**Comment by RedLime** [comment]
that issues on my works too.

**Comment by modderwizard** [comment]
@kyrptonaught I figured out how to fix this issue.

In order to fix the issue you need a Mixin accessor for Entity.unsetRemoved(), and call it in CustomTeleporter after
`serverWorld.removePlayer(player, EntityRemovalReason.CHANGED_DIMENSION`

I don't know if you accept pull requests from other people, but just let me know if you want me to submit a pull request with the changes I made.

**Comment by kyrptonaught** [comment]
I do accept pull requests! I'll gladly take some help! Can you verify that this works on the most recent snapshot? Assuming you discovered this by checking the vanilla teleportation logic?

**Comment by modderwizard** [comment]
Verified that it works on 21w05a as well. Submitted a pull request to fix. Wasn't sure how to link the pull request to this issue since I've never submitted a pull request before :P

**Comment by kyrptonaught** [comment]
Thanks! I'll check over it in a bit.

You can mention the pr just by stating it's number, this works in both directions too. You can mention an issue in a pr. For example: #9

**Comment by RedLime** [comment]
is it fixed or closed issue?

**Comment by kyrptonaught** [comment]
I have not gotten the chance to submit a new build to bintray yet

**Comment by kyrptonaught** [comment]
Thank you for your help. 0.0.1-beta21-1.17 was uploaded to bintray with this fix implemented
