### ISSUE TITLE
Server crash when player joins

### ISSUE THREAD

**Issue by netfix9** [kyrptonaught/customportalapi#89]
[https://www.reddit.com/r/admincraft/comments/18l25ih/server_crashes_when_a_player_joins/](url)

i dont want to type it again, all the details are there

**Comment by netfix9** [comment]
heres crash report btw
[https://pastebin.com/6SRMt1sM](url)

**Comment by kyrptonaught** [comment]
Something must of changed in fabric api. Please use version: `0.0.1-beta64.5-1.20.2`

**Comment by netfix9** [comment]
how do i update the version as a repository of deeper and darker
