### ISSUE TITLE
Default nether portal gets replaced by custom one that teleports to the end dimension

### ISSUE THREAD

**Issue by prplrose** [kyrptonaught/customportalapi#99]
Steps to reproduce:
1. Create new Minecraft Mod project
2. Add Custom Portal API dependency to build.gradle
3. Run runClient task
4. Create new world
5. Build standard 2x3 nether portal
6. Light it up (for example with flint and steel or fire charge)

![2024-05-06_00 19 37](https://github.com/kyrptonaught/customportalapi/assets/158543118/d1f99350-c083-4b42-984a-da8305fdf93e)

Minecraft version: 1.20.5
Fabric loader version: 0.15.11
Fabric API version: 0.97.8+1.20.5

Suggested fix: [Pull request](https://github.com/kyrptonaught/customportalapi/pull/98) removing registrations of custom portals in [CustomPortalsMod.java](https://github.com/kyrptonaught/customportalapi/blob/1.20.5/src/main/java/net/kyrptonaught/customportalapi/CustomPortalsMod.java)

**Comment by kyrptonaught** [comment]
Fixed in 65.5.

Thank you for the fix
